apiVersion: 1
datasources:
  - name: prometheus-ec2
    type: prometheus
    access: proxy
    url: http://prometheus-server.service.final-project.consul:9090
    isDefault: true
  - name: Prometheus-eks
    type: prometheus
    access: proxy
    url: http://prometheus-server-monitoring.service.final-project.consul:9090
    isDefault: false
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    orgId: 1
    jsonData:
      defaultRegion: "us-east-1"
    version: 1
    editable: false