# filebeat.inputs:
#   - type: log
#     enabled: false
#     paths:
#       - /var/log/*.log
#       - /var/log/auth.log
#       - /var/log/syslog
  # - type: container
  #   enabled: false
  #   paths:
  #     - "/var/lib/docker/containers/*/*.log"
filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            regexp:
              docker.container.image: ".*" # all other containers
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              processors:
                - decode_json_fields:
                    fields: ["message"]
                    max_depth: 1
                    target: ""
                    overwrite_keys: true
                    when:
                      regexp:
                        message: '^{'
filebeat.modules:
  - module: system
    syslog:
      enabled: true
    auth:
      enabled: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.dashboards.enabled: true
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.template.settings:
  index.number_of_shards: 1

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
#  - add_docker_metadata:
#      host: "unix://var/run/docker.sock"

output.elasticsearch:
  hosts: [ "localhost:9200" ]
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.kibana.host: "localhost:5601"
setup.kibana.protocol: "http"